// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrOpen_screen_init(void)
{
    ui_scrOpen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrOpen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrOpen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrOpen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_scrOpen);
    lv_img_set_src(ui_logo, &ui_img_1718244669);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 122
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 106
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_logo, 128);

    lv_obj_add_event_cb(ui_scrOpen, ui_event_scrOpen, LV_EVENT_ALL, NULL);

}
