// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrTomato_screen_init(void)
{
    ui_scrTomato = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrTomato, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrTomato, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrTomato, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrTomato, &ui_img_background_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcTomato = lv_arc_create(ui_scrTomato);
    lv_obj_set_width(ui_arcTomato, 210);
    lv_obj_set_height(ui_arcTomato, 210);
    lv_obj_set_align(ui_arcTomato, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arcTomato, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_arcTomato, 0);
    lv_arc_set_bg_angles(ui_arcTomato, 150, 30);

    lv_obj_set_style_arc_color(ui_arcTomato, lv_color_hex(0xB12323), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcTomato, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcTomato, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcTomato, lv_color_hex(0x0F0202), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcTomato, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_arcTomato, &ui_img_1249513910, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_labelTomatoecond = lv_label_create(ui_scrTomato);
    lv_obj_set_width(ui_labelTomatoecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTomatoecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTomatoecond, 38);
    lv_obj_set_y(ui_labelTomatoecond, -5);
    lv_obj_set_align(ui_labelTomatoecond, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTomatoecond, "00");
    lv_obj_set_style_text_font(ui_labelTomatoecond, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTomatoMin = lv_label_create(ui_scrTomato);
    lv_obj_set_width(ui_labelTomatoMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTomatoMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTomatoMin, -41);
    lv_obj_set_y(ui_labelTomatoMin, -5);
    lv_obj_set_align(ui_labelTomatoMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTomatoMin, "25");
    lv_obj_set_style_text_font(ui_labelTomatoMin, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTomatoDot = lv_label_create(ui_scrTomato);
    lv_obj_set_width(ui_labelTomatoDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTomatoDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTomatoDot, -2);
    lv_obj_set_y(ui_labelTomatoDot, -6);
    lv_obj_set_align(ui_labelTomatoDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTomatoDot, ":");
    lv_obj_set_style_text_font(ui_labelTomatoDot, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTomatoStart = lv_img_create(ui_scrTomato);
    lv_img_set_src(ui_imgTomatoStart, &ui_img_kaishi1_png);
    lv_obj_set_width(ui_imgTomatoStart, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgTomatoStart, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_imgTomatoStart, -1);
    lv_obj_set_y(ui_imgTomatoStart, 68);
    lv_obj_set_align(ui_imgTomatoStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTomatoStart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTomatoStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTomatoPause = lv_img_create(ui_scrTomato);
    lv_img_set_src(ui_imgTomatoPause, &ui_img_ai07_png);
    lv_obj_set_width(ui_imgTomatoPause, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgTomatoPause, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_imgTomatoPause, -1);
    lv_obj_set_y(ui_imgTomatoPause, 68);
    lv_obj_set_align(ui_imgTomatoPause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTomatoPause, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTomatoPause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTomatoCount = lv_img_create(ui_scrTomato);
    lv_img_set_src(ui_imgTomatoCount, &ui_img_fanqie_new_png);
    lv_obj_set_width(ui_imgTomatoCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTomatoCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTomatoCount, -13);
    lv_obj_set_y(ui_imgTomatoCount, -54);
    lv_obj_set_align(ui_imgTomatoCount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTomatoCount, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTomatoCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelTomatoCount = lv_label_create(ui_scrTomato);
    lv_obj_set_width(ui_labelTomatoCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTomatoCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTomatoCount, 18);
    lv_obj_set_y(ui_labelTomatoCount, -55);
    lv_obj_set_align(ui_labelTomatoCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTomatoCount, "0");
    lv_obj_set_style_text_font(ui_labelTomatoCount, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTomatoX = lv_label_create(ui_scrTomato);
    lv_obj_set_width(ui_labelTomatoX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTomatoX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTomatoX, 5);
    lv_obj_set_y(ui_labelTomatoX, -56);
    lv_obj_set_align(ui_labelTomatoX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTomatoX, "x");
    lv_obj_set_style_text_font(ui_labelTomatoX, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_scrTomato, ui_event_scrTomato, LV_EVENT_ALL, NULL);

}
