// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrLight_screen_init(void)
{
    ui_scrLight = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrLight, &ui_img_background_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_scrLight);
    lv_obj_set_width(ui_Panel8, lv_pct(96));
    lv_obj_set_height(ui_Panel8, lv_pct(94));
    lv_obj_set_x(ui_Panel8, 20);
    lv_obj_set_y(ui_Panel8, 10);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel8, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel8, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel8, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Panel5, lv_pct(88));
    lv_obj_set_height(ui_Panel5, lv_pct(39));
    lv_obj_set_x(ui_Panel5, 1);
    lv_obj_set_y(ui_Panel5, -100);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xEE2525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PalLightSetting = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_PalLightSetting, lv_pct(118));
    lv_obj_set_height(ui_PalLightSetting, lv_pct(114));
    lv_obj_set_x(ui_PalLightSetting, -1);
    lv_obj_set_y(ui_PalLightSetting, -30);
    lv_obj_set_align(ui_PalLightSetting, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PalLightSetting, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PalLightSetting, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PalLightSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PalLightSetting, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PalLightSetting, lv_color_hex(0x111717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PalLightSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PalLightSetting, lv_color_hex(0x2BD1EE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_PalLightSetting, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_PalLightSetting, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_PalLightSetting, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image16 = lv_img_create(ui_PalLightSetting);
    lv_img_set_src(ui_Image16, &ui_img_shezhi_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image16, 3);
    lv_obj_set_y(ui_Image16, 20);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Image16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_PalLightSetting);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "灯效设置");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PalLightBreath = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_PalLightBreath, lv_pct(88));
    lv_obj_set_height(ui_PalLightBreath, lv_pct(25));
    lv_obj_set_x(ui_PalLightBreath, -1);
    lv_obj_set_y(ui_PalLightBreath, -30);
    lv_obj_set_align(ui_PalLightBreath, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PalLightBreath, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PalLightBreath, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PalLightBreath, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PalLightBreath, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PalLightBreath, lv_color_hex(0x111717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PalLightBreath, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PalLightBreath, lv_color_hex(0x2BD1EE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_PalLightBreath, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_PalLightBreath, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_PalLightBreath, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image3 = lv_img_create(ui_PalLightBreath);
    lv_img_set_src(ui_Image3, &ui_img_1_round_solid_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image3, 3);
    lv_obj_set_y(ui_Image3, 20);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Image3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_PalLightBreath);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "呼吸效果");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PalLightFluid = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_PalLightFluid, lv_pct(88));
    lv_obj_set_height(ui_PalLightFluid, lv_pct(25));
    lv_obj_set_x(ui_PalLightFluid, -1);
    lv_obj_set_y(ui_PalLightFluid, -30);
    lv_obj_set_align(ui_PalLightFluid, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PalLightFluid, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PalLightFluid, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PalLightFluid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PalLightFluid, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PalLightFluid, lv_color_hex(0x101410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PalLightFluid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PalLightFluid, lv_color_hex(0x2BD1EE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_PalLightFluid, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_PalLightFluid, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_PalLightFluid, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image5 = lv_img_create(ui_PalLightFluid);
    lv_img_set_src(ui_Image5, &ui_img_2_round_solid_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image5, 3);
    lv_obj_set_y(ui_Image5, 20);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Image5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_PalLightFluid);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "流水效果");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PalLightRainbow = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_PalLightRainbow, lv_pct(88));
    lv_obj_set_height(ui_PalLightRainbow, lv_pct(25));
    lv_obj_set_x(ui_PalLightRainbow, -1);
    lv_obj_set_y(ui_PalLightRainbow, -30);
    lv_obj_set_align(ui_PalLightRainbow, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PalLightRainbow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PalLightRainbow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PalLightRainbow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PalLightRainbow, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PalLightRainbow, lv_color_hex(0x101410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PalLightRainbow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PalLightRainbow, lv_color_hex(0x2BD1EE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_PalLightRainbow, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_PalLightRainbow, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_PalLightRainbow, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image10 = lv_img_create(ui_PalLightRainbow);
    lv_img_set_src(ui_Image10, &ui_img_3_round_solid_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_PalLightRainbow);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "彩虹渐变");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PalLightSky = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_PalLightSky, lv_pct(88));
    lv_obj_set_height(ui_PalLightSky, lv_pct(25));
    lv_obj_set_x(ui_PalLightSky, -1);
    lv_obj_set_y(ui_PalLightSky, -30);
    lv_obj_set_align(ui_PalLightSky, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PalLightSky, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PalLightSky, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PalLightSky, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PalLightSky, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PalLightSky, lv_color_hex(0x101410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PalLightSky, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PalLightSky, lv_color_hex(0x2BD1EE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_PalLightSky, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_PalLightSky, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_PalLightSky, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image13 = lv_img_create(ui_PalLightSky);
    lv_img_set_src(ui_Image13, &ui_img_4_round_solid_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_PalLightSky);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "星空闪烁");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PalLightFramwork = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_PalLightFramwork, lv_pct(88));
    lv_obj_set_height(ui_PalLightFramwork, lv_pct(25));
    lv_obj_set_x(ui_PalLightFramwork, -1);
    lv_obj_set_y(ui_PalLightFramwork, -30);
    lv_obj_set_align(ui_PalLightFramwork, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PalLightFramwork, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PalLightFramwork, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PalLightFramwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PalLightFramwork, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PalLightFramwork, lv_color_hex(0x101410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PalLightFramwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PalLightFramwork, lv_color_hex(0x2BD1EE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_PalLightFramwork, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_PalLightFramwork, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_PalLightFramwork, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image14 = lv_img_create(ui_PalLightFramwork);
    lv_img_set_src(ui_Image14, &ui_img_5_round_solid_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_PalLightFramwork);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "烟花绽放");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Panel6, lv_pct(88));
    lv_obj_set_height(ui_Panel6, lv_pct(25));
    lv_obj_set_x(ui_Panel6, 93);
    lv_obj_set_y(ui_Panel6, 26);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PalLightSetting, ui_event_PalLightSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PalLightBreath, ui_event_PalLightBreath, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PalLightFluid, ui_event_PalLightFluid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PalLightRainbow, ui_event_PalLightRainbow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PalLightSky, ui_event_PalLightSky, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrLight, ui_event_scrLight, LV_EVENT_ALL, NULL);

}
