// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrMusic_screen_init(void)
{
    ui_scrMusic = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrMusic, &ui_img_background_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgLastMusic = lv_img_create(ui_scrMusic);
    lv_img_set_src(ui_imgLastMusic, &ui_img_lastmusic_png);
    lv_obj_set_width(ui_imgLastMusic, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgLastMusic, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_imgLastMusic, -70);
    lv_obj_set_y(ui_imgLastMusic, 0);
    lv_obj_set_align(ui_imgLastMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLastMusic, LV_OBJ_FLAG_CLICKABLE |LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgLastMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgLastMusic, 200);

    ui_imgNextMusic = lv_img_create(ui_scrMusic);
    lv_img_set_src(ui_imgNextMusic, &ui_img_nextmusic_png);
    lv_obj_set_width(ui_imgNextMusic, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgNextMusic, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_imgNextMusic, 70);
    lv_obj_set_y(ui_imgNextMusic, 0);
    lv_obj_set_align(ui_imgNextMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgNextMusic, LV_OBJ_FLAG_CLICKABLE |LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgNextMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgNextMusic, 200);

    ui_imgStartMusic = lv_img_create(ui_scrMusic);
    lv_img_set_src(ui_imgStartMusic, &ui_img_bofangmusic_png);
    lv_obj_set_width(ui_imgStartMusic, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_imgStartMusic, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_imgStartMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgStartMusic, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE |LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgStartMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgStartMusic, 350);

    ui_imgEndMusic = lv_img_create(ui_scrMusic);
    lv_img_set_src(ui_imgEndMusic, &ui_img_zantingmusic_png);
    lv_obj_set_width(ui_imgEndMusic, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_imgEndMusic, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_imgEndMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgEndMusic, LV_OBJ_FLAG_CLICKABLE |LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgEndMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgEndMusic, 350);

    ui_labMusicHour = lv_label_create(ui_scrMusic);
    lv_obj_set_width(ui_labMusicHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labMusicHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labMusicHour, -20);
    lv_obj_set_y(ui_labMusicHour, -80);
    lv_obj_set_align(ui_labMusicHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMusicHour, "03");
    lv_obj_set_style_text_font(ui_labMusicHour, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labMusicMin = lv_label_create(ui_scrMusic);
    lv_obj_set_width(ui_labMusicMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labMusicMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labMusicMin, 20);
    lv_obj_set_y(ui_labMusicMin, -80);
    lv_obj_set_align(ui_labMusicMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMusicMin, "27");
    lv_obj_set_style_text_font(ui_labMusicMin, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labMusicDot = lv_label_create(ui_scrMusic);
    lv_obj_set_width(ui_labMusicDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labMusicDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labMusicDot, 0);
    lv_obj_set_y(ui_labMusicDot, -80);
    lv_obj_set_align(ui_labMusicDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMusicDot, ":");
    lv_obj_set_style_text_font(ui_labMusicDot, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgSound = lv_img_create(ui_scrMusic);
    lv_img_set_src(ui_imgSound, &ui_img_yinliang_png);
    lv_obj_set_width(ui_imgSound, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgSound, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_imgSound, 0);
    lv_obj_set_y(ui_imgSound, 75);
    lv_obj_set_align(ui_imgSound, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgSound, LV_OBJ_FLAG_CLICKABLE |LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgSound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMute = lv_img_create(ui_scrMusic);
    lv_img_set_src(ui_imgMute, &ui_img_jingyin_png);
    lv_obj_set_width(ui_imgMute, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgMute, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_imgMute, 0);
    lv_obj_set_y(ui_imgMute, 75);
    lv_obj_set_align(ui_imgMute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMute, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE |LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_scrMusic, ui_event_scrMusic, LV_EVENT_ALL, NULL);

}
