// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrWatchSelect_screen_init(void)
{
    ui_scrWatchSelect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrWatchSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_scrWatchSelect);
    lv_obj_set_width(ui_Panel4, 450);
    lv_obj_set_height(ui_Panel4, 273);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWatch4 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_imgWatch4, &ui_img_bias_png);
    lv_obj_set_width(ui_imgWatch4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWatch4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWatch4, -46);
    lv_obj_set_y(ui_imgWatch4, -14);
    lv_obj_set_align(ui_imgWatch4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_imgWatch4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_imgWatch4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_imgWatch4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWatch4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgWatch1 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_imgWatch1, &ui_img_watch1_170_png);
    lv_obj_set_width(ui_imgWatch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWatch1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWatch1, -46);
    lv_obj_set_y(ui_imgWatch1, -14);
    lv_obj_set_align(ui_imgWatch1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_imgWatch1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_imgWatch1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_imgWatch1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWatch1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgWatch2 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_imgWatch2, &ui_img_watch2_170_png);
    lv_obj_set_width(ui_imgWatch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWatch2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWatch2, 49);
    lv_obj_set_y(ui_imgWatch2, -4);
    lv_obj_set_align(ui_imgWatch2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_imgWatch2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_imgWatch2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_imgWatch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWatch2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgWatch3 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_imgWatch3, &ui_img_bias_png);
    lv_obj_set_width(ui_imgWatch3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWatch3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWatch3, 49);
    lv_obj_set_y(ui_imgWatch3, -4);
    lv_obj_set_align(ui_imgWatch3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_imgWatch3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_imgWatch3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_imgWatch3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWatch3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_imgWatch1, ui_event_imgWatch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgWatch2, ui_event_imgWatch2, LV_EVENT_ALL, NULL);

}
