// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrWatch2_screen_init(void)
{
    ui_scrWatch2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrWatch2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrWatch2, &ui_img_background2_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge1 = lv_img_create(ui_scrWatch2);
    lv_img_set_src(ui_charge1, &ui_img_flash_png);
    lv_obj_set_width(ui_charge1, LV_SIZE_CONTENT);   /// 13
    lv_obj_set_height(ui_charge1, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_charge1, -17);
    lv_obj_set_y(ui_charge1, -102);
    lv_obj_set_align(ui_charge1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_charge1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_charge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_charge1, 180);

    ui_labPower2 = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labPower2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labPower2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labPower2, 7);
    lv_obj_set_y(ui_labPower2, -103);
    lv_obj_set_align(ui_labPower2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labPower2, "86%");
    lv_obj_set_style_text_font(ui_labPower2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_red_bar3 = lv_img_create(ui_scrWatch2);
    lv_img_set_src(ui_red_bar3, &ui_img_btn_bg_1_png);
    lv_obj_set_width(ui_red_bar3, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_red_bar3, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_red_bar3, 94);
    lv_obj_set_y(ui_red_bar3, -67);
    lv_obj_set_align(ui_red_bar3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red_bar3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_red_bar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_red_bar3, 157);

    ui_red_bar4 = lv_img_create(ui_scrWatch2);
    lv_img_set_src(ui_red_bar4, &ui_img_btn_bg_3_png);
    lv_obj_set_width(ui_red_bar4, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_red_bar4, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_red_bar4, 95);
    lv_obj_set_y(ui_red_bar4, 65);
    lv_obj_set_align(ui_red_bar4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red_bar4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_red_bar4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_red_bar4, 157);

    ui_imgCloudy2 = lv_img_create(ui_scrWatch2);
    lv_img_set_src(ui_imgCloudy2, &ui_img_weather_cloud_png);
    lv_obj_set_width(ui_imgCloudy2, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_imgCloudy2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_imgCloudy2, -31);
    lv_obj_set_y(ui_imgCloudy2, 40);
    lv_obj_set_align(ui_imgCloudy2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgCloudy2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgCloudy2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgCloudy2, 200);

    ui_labTemp2 = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labTemp2, -62);
    lv_obj_set_y(ui_labTemp2, 42);
    lv_obj_set_align(ui_labTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labTemp2, "25°");
    lv_obj_set_style_text_font(ui_labTemp2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labWeek2 = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labWeek2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labWeek2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labWeek2, 39);
    lv_obj_set_y(ui_labWeek2, -60);
    lv_obj_set_align(ui_labWeek2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labWeek2, "MON");

    ui_labDate2 = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labDate2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labDate2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labDate2, 42);
    lv_obj_set_y(ui_labDate2, -39);
    lv_obj_set_align(ui_labDate2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labDate2, "1 JULY");

    ui_labTimeHour2 = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labTimeHour2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labTimeHour2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labTimeHour2, -76);
    lv_obj_set_y(ui_labTimeHour2, -29);
    lv_obj_set_align(ui_labTimeHour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labTimeHour2, "0");
    lv_obj_set_style_text_color(ui_labTimeHour2, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labTimeHour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labTimeHour2, &ui_font_Number_Large, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labTimeHour1 = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labTimeHour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labTimeHour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labTimeHour1, -18);
    lv_obj_set_y(ui_labTimeHour1, -28);
    lv_obj_set_align(ui_labTimeHour1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labTimeHour1, "3");
    lv_obj_set_style_text_color(ui_labTimeHour1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labTimeHour1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labTimeHour1, &ui_font_Number_Large, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labTimeMin = lv_label_create(ui_scrWatch2);
    lv_obj_set_width(ui_labTimeMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labTimeMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labTimeMin, 47);
    lv_obj_set_y(ui_labTimeMin, 39);
    lv_obj_set_align(ui_labTimeMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labTimeMin, "27");
    lv_obj_set_style_text_color(ui_labTimeMin, lv_color_hex(0xFF0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labTimeMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labTimeMin, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec_dot = lv_img_create(ui_scrWatch2);
    lv_img_set_src(ui_sec_dot, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_sec_dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec_dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec_dot, 0);
    lv_obj_set_y(ui_sec_dot, -190);
    lv_obj_set_align(ui_sec_dot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sec_dot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sec_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_sec_dot, 4, 194);
    lv_img_set_zoom(ui_sec_dot, 157);

    lv_obj_add_event_cb(ui_scrWatch2, ui_event_scrWatch2, LV_EVENT_ALL, NULL);

}
