// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrUpdate_screen_init(void)
{
    ui_scrUpdate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrUpdate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrUpdate, &ui_img_background_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelAlready = lv_obj_create(ui_scrUpdate);
    lv_obj_set_width(ui_panelAlready, 146);
    lv_obj_set_height(ui_panelAlready, 96);
    lv_obj_set_align(ui_panelAlready, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelAlready, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_panelAlready, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_panelAlready, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_panelAlready, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelAlready, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelAlready, lv_color_hex(0x4D4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelAlready, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate2 = lv_label_create(ui_panelAlready);
    lv_obj_set_width(ui_labUpdate2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate2, -2);
    lv_obj_set_y(ui_labUpdate2, -27);
    lv_obj_set_align(ui_labUpdate2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate2, "已是最新版本");
    lv_obj_set_style_text_font(ui_labUpdate2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate3 = lv_label_create(ui_panelAlready);
    lv_obj_set_width(ui_labUpdate3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate3, -3);
    lv_obj_set_y(ui_labUpdate3, 5);
    lv_obj_set_align(ui_labUpdate3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate3, "EK3_release_1.0");
    lv_obj_set_style_text_font(ui_labUpdate3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelNewVersion = lv_obj_create(ui_scrUpdate);
    lv_obj_set_width(ui_panelNewVersion, 256);
    lv_obj_set_height(ui_panelNewVersion, 250);
    lv_obj_set_align(ui_panelNewVersion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_panelNewVersion, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_panelNewVersion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelNewVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelNewVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelAlready1 = lv_obj_create(ui_panelNewVersion);
    lv_obj_set_width(ui_panelAlready1, 146);
    lv_obj_set_height(ui_panelAlready1, 96);
    lv_obj_set_x(ui_panelAlready1, -1);
    lv_obj_set_y(ui_panelAlready1, -15);
    lv_obj_set_align(ui_panelAlready1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelAlready1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_panelAlready1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelAlready1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelAlready1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelAlready1, lv_color_hex(0x4D4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelAlready1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate4 = lv_label_create(ui_panelAlready1);
    lv_obj_set_width(ui_labUpdate4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate4, -2);
    lv_obj_set_y(ui_labUpdate4, -27);
    lv_obj_set_align(ui_labUpdate4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate4, "发现最新版本");
    lv_obj_set_style_text_font(ui_labUpdate4, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate5 = lv_label_create(ui_panelAlready1);
    lv_obj_set_width(ui_labUpdate5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate5, -3);
    lv_obj_set_y(ui_labUpdate5, 5);
    lv_obj_set_align(ui_labUpdate5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate5, "EK3_release_1.1");
    lv_obj_set_style_text_font(ui_labUpdate5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpdate = lv_btn_create(ui_panelNewVersion);
    lv_obj_set_width(ui_buttonUpdate, 60);
    lv_obj_set_height(ui_buttonUpdate, 40);
    lv_obj_set_x(ui_buttonUpdate, -37);
    lv_obj_set_y(ui_buttonUpdate, 62);
    lv_obj_set_align(ui_buttonUpdate, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_buttonUpdate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonUpdate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonUpdate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate = lv_label_create(ui_panelNewVersion);
    lv_obj_set_width(ui_labUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate, -38);
    lv_obj_set_y(ui_labUpdate, 61);
    lv_obj_set_align(ui_labUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate, "更新");
    lv_obj_set_style_text_font(ui_labUpdate, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonCancel = lv_btn_create(ui_panelNewVersion);
    lv_obj_set_width(ui_buttonCancel, 60);
    lv_obj_set_height(ui_buttonCancel, 40);
    lv_obj_set_x(ui_buttonCancel, 33);
    lv_obj_set_y(ui_buttonCancel, 62);
    lv_obj_set_align(ui_buttonCancel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_buttonCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonCancel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labCancel = lv_label_create(ui_panelNewVersion);
    lv_obj_set_width(ui_labCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labCancel, 32);
    lv_obj_set_y(ui_labCancel, 61);
    lv_obj_set_align(ui_labCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labCancel, "取消");
    lv_obj_set_style_text_font(ui_labCancel, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelCheckUpdate = lv_obj_create(ui_scrUpdate);
    lv_obj_set_width(ui_panelCheckUpdate, 146);
    lv_obj_set_height(ui_panelCheckUpdate, 96);
    lv_obj_set_align(ui_panelCheckUpdate, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelCheckUpdate, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_panelCheckUpdate, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelCheckUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelCheckUpdate, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelCheckUpdate, lv_color_hex(0x4D4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelCheckUpdate, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate1 = lv_label_create(ui_panelCheckUpdate);
    lv_obj_set_width(ui_labUpdate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate1, -7);
    lv_obj_set_y(ui_labUpdate1, -4);
    lv_obj_set_align(ui_labUpdate1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate1, "正在检测更新");
    lv_obj_set_style_text_font(ui_labUpdate1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spinUpdate = lv_spinner_create(ui_panelCheckUpdate, 1000, 90);
    lv_obj_set_width(ui_spinUpdate, 30);
    lv_obj_set_height(ui_spinUpdate, 30);
    lv_obj_set_x(ui_spinUpdate, -7);
    lv_obj_set_y(ui_spinUpdate, 36);
    lv_obj_set_align(ui_spinUpdate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_spinUpdate, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_spinUpdate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_spinUpdate, lv_color_hex(0xF9FDFE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinUpdate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinUpdate, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_panelNoConnect = lv_obj_create(ui_scrUpdate);
    lv_obj_set_width(ui_panelNoConnect, 146);
    lv_obj_set_height(ui_panelNoConnect, 96);
    lv_obj_set_align(ui_panelNoConnect, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelNoConnect, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_panelNoConnect, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelNoConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_panelNoConnect, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_panelNoConnect, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelNoConnect, lv_color_hex(0x4D4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelNoConnect, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUpdate6 = lv_label_create(ui_panelNoConnect);
    lv_obj_set_width(ui_labUpdate6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUpdate6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUpdate6, -7);
    lv_obj_set_y(ui_labUpdate6, -4);
    lv_obj_set_align(ui_labUpdate6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUpdate6, "请在屏幕关闭后\n长按开关键5s");
    lv_obj_set_style_text_font(ui_labUpdate6, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_scrUpdate, ui_event_scrUpdate, LV_EVENT_ALL, NULL);

}
