// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrTimer_screen_init(void)
{
    ui_scrTimer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrTimer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrTimer, &ui_img_background_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimerSecond1 = lv_label_create(ui_scrTimer);
    lv_obj_set_width(ui_labelTimerSecond1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerSecond1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerSecond1, 74);
    lv_obj_set_y(ui_labelTimerSecond1, -8);
    lv_obj_set_align(ui_labelTimerSecond1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerSecond1, "00");
    lv_obj_set_style_text_font(ui_labelTimerSecond1, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimerMin1 = lv_label_create(ui_scrTimer);
    lv_obj_set_width(ui_labelTimerMin1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerMin1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerMin1, 0);
    lv_obj_set_y(ui_labelTimerMin1, -8);
    lv_obj_set_align(ui_labelTimerMin1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerMin1, "00");
    lv_obj_set_style_text_font(ui_labelTimerMin1, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimerHour1 = lv_label_create(ui_scrTimer);
    lv_obj_set_width(ui_labelTimerHour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerHour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerHour1, -72);
    lv_obj_set_y(ui_labelTimerHour1, -8);
    lv_obj_set_align(ui_labelTimerHour1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerHour1, "00");
    lv_obj_set_style_text_font(ui_labelTimerHour1, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimerDot1 = lv_label_create(ui_scrTimer);
    lv_obj_set_width(ui_labelTimerDot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerDot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerDot1, 34);
    lv_obj_set_y(ui_labelTimerDot1, -7);
    lv_obj_set_align(ui_labelTimerDot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerDot1, ":");
    lv_obj_set_style_text_font(ui_labelTimerDot1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimerDot2 = lv_label_create(ui_scrTimer);
    lv_obj_set_width(ui_labelTimerDot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerDot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerDot2, -38);
    lv_obj_set_y(ui_labelTimerDot2, -7);
    lv_obj_set_align(ui_labelTimerDot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerDot2, ":");
    lv_obj_set_style_text_font(ui_labelTimerDot2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTimerStart = lv_img_create(ui_scrTimer);
    lv_img_set_src(ui_imgTimerStart, &ui_img_kaishi_png);
    lv_obj_set_width(ui_imgTimerStart, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgTimerStart, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_imgTimerStart, -37);
    lv_obj_set_y(ui_imgTimerStart, 59);
    lv_obj_set_align(ui_imgTimerStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTimerStart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTimerStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTimerPause = lv_img_create(ui_scrTimer);
    lv_img_set_src(ui_imgTimerPause, &ui_img_ai07_png);
    lv_obj_set_width(ui_imgTimerPause, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgTimerPause, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_imgTimerPause, -37);
    lv_obj_set_y(ui_imgTimerPause, 59);
    lv_obj_set_align(ui_imgTimerPause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTimerPause, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTimerPause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTimerRst = lv_img_create(ui_scrTimer);
    lv_img_set_src(ui_imgTimerRst, &ui_img_238951591);
    lv_obj_set_width(ui_imgTimerRst, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTimerRst, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTimerRst, 30);
    lv_obj_set_y(ui_imgTimerRst, 59);
    lv_obj_set_align(ui_imgTimerRst, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTimerRst, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTimerRst, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_scrTimer, ui_event_scrTimer, LV_EVENT_ALL, NULL);

}
