// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrOpen
void ui_scrOpen_screen_init(void);
void ui_event_scrOpen(lv_event_t * e);
lv_obj_t * ui_scrOpen;
lv_obj_t * ui_logo;
lv_obj_t * ui_labOpen;
lv_obj_t * ui_pannelOpen;
lv_obj_t * ui_Label6;
lv_obj_t * ui_spinOpen;


// SCREEN: ui_scrWatch1
void ui_scrWatch1_screen_init(void);
void ui_event_scrWatch1(lv_event_t * e);
lv_obj_t * ui_scrWatch1;
lv_obj_t * ui_imgCharge;
lv_obj_t * ui_labPower;
lv_obj_t * ui_red_bar1;
lv_obj_t * ui_red_bar2;
lv_obj_t * ui_imgWatch1Cloudy;
lv_obj_t * ui_labTemp;
lv_obj_t * ui_labWeek;
lv_obj_t * ui_labDate;
lv_obj_t * ui_hour;
lv_obj_t * ui_sec;
lv_obj_t * ui_min;
lv_obj_t * ui_imgWatch1Rainy;
lv_obj_t * ui_imgWatch1Sunny;
lv_obj_t * ui_imgWatch1Snow;
lv_obj_t * ui_ArcPower1;
lv_obj_t * ui_dotWatch11;
lv_obj_t * ui_dotWatch12;


// SCREEN: ui_scrWatch2
void ui_scrWatch2_screen_init(void);
void ui_event_scrWatch2(lv_event_t * e);
lv_obj_t * ui_scrWatch2;
lv_obj_t * ui_imgCharge2;
lv_obj_t * ui_labPower2;
lv_obj_t * ui_red_bar3;
lv_obj_t * ui_red_bar4;
lv_obj_t * ui_imgWatch2Cloudy;
lv_obj_t * ui_labTemp2;
lv_obj_t * ui_labWeek2;
lv_obj_t * ui_labDate2;
lv_obj_t * ui_labTimeHour2;
lv_obj_t * ui_labTimeHour1;
lv_obj_t * ui_labTimeMin;
lv_obj_t * ui_sec_dot;
lv_obj_t * ui_imgWatch2Sunny;
lv_obj_t * ui_imgWatch2Rainy;
lv_obj_t * ui_imgWatch2Snow;
lv_obj_t * ui_ArcPower2;
lv_obj_t * ui_dotWatch21;
lv_obj_t * ui_dotWatch22;


// SCREEN: ui_scrWeather
void ui_scrWeather_screen_init(void);
void ui_event_scrWeather(lv_event_t * e);
lv_obj_t * ui_scrWeather;
lv_obj_t * ui_imgWeatherHum;
lv_obj_t * ui_labWeatherTemp;
lv_obj_t * ui_labWeatherHum;
lv_obj_t * ui_labWeatherArea;
lv_obj_t * ui_labWeatherTianqi;
lv_obj_t * ui_labWeatherMaxmin;
lv_obj_t * ui_labWeatherDate;
lv_obj_t * ui_imgWeatherRainy;
lv_obj_t * ui_imgWeatherSnow;
lv_obj_t * ui_imgWeatherCloudy;
lv_obj_t * ui_imgWeatherSunny;


// SCREEN: ui_scrTimer
void ui_scrTimer_screen_init(void);
void ui_event_scrTimer(lv_event_t * e);
lv_obj_t * ui_scrTimer;
lv_obj_t * ui_labelTimerSecond1;
lv_obj_t * ui_labelTimerMin1;
lv_obj_t * ui_labelTimerHour1;
lv_obj_t * ui_labelTimerDot1;
lv_obj_t * ui_labelTimerDot2;
lv_obj_t * ui_imgTimerStart;
lv_obj_t * ui_imgTimerPause;
lv_obj_t * ui_imgTimerRst;


// SCREEN: ui_scrTomato
void ui_scrTomato_screen_init(void);
void ui_event_scrTomato(lv_event_t * e);
lv_obj_t * ui_scrTomato;
lv_obj_t * ui_arcTomato;
lv_obj_t * ui_labelTomatoecond;
lv_obj_t * ui_labelTomatoMin;
lv_obj_t * ui_labelTomatoDot;
lv_obj_t * ui_imgTomatoStart;
lv_obj_t * ui_imgTomatoPause;
lv_obj_t * ui_imgTomatoCount;
lv_obj_t * ui_labelTomatoCount;
lv_obj_t * ui_labelTomatoX;


// SCREEN: ui_scrMenu
void ui_scrMenu_screen_init(void);
void ui_event_scrMenu(lv_event_t * e);
lv_obj_t * ui_scrMenu;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
void ui_event_PalWatch2(lv_event_t * e);
lv_obj_t * ui_PalWatch2;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label15;
void ui_event_PalMusic(lv_event_t * e);
lv_obj_t * ui_PalMusic;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Label2;
void ui_event_PalWeather(lv_event_t * e);
lv_obj_t * ui_PalWeather;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label9;
void ui_event_PalTimer(lv_event_t * e);
lv_obj_t * ui_PalTimer;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label10;
void ui_event_PalTomato(lv_event_t * e);
lv_obj_t * ui_PalTomato;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label11;
void ui_event_PalLight(lv_event_t * e);
lv_obj_t * ui_PalLight;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label12;
void ui_event_PalUpdate(lv_event_t * e);
lv_obj_t * ui_PalUpdate;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel3;


// SCREEN: ui_scrLight
void ui_scrLight_screen_init(void);
void ui_event_scrLight(lv_event_t * e);
lv_obj_t * ui_scrLight;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_PalLightSetting;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label20;
lv_obj_t * ui_PalLightBreath;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label13;
lv_obj_t * ui_PalLightStay;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label14;
lv_obj_t * ui_PalLightRainbow;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label16;
lv_obj_t * ui_PalLightSky;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label17;
lv_obj_t * ui_PalLightWave;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Panel6;


// SCREEN: ui_scrUpdate
void ui_scrUpdate_screen_init(void);
void ui_event_scrUpdate(lv_event_t * e);
lv_obj_t * ui_scrUpdate;
lv_obj_t * ui_panelAlready;
lv_obj_t * ui_labUpdate2;
lv_obj_t * ui_labUpdate3;
lv_obj_t * ui_panelNewVersion;
lv_obj_t * ui_panelAlready1;
lv_obj_t * ui_labUpdate4;
lv_obj_t * ui_labUpdate5;
lv_obj_t * ui_buttonUpdate;
lv_obj_t * ui_labUpdate;
lv_obj_t * ui_buttonCancel;
lv_obj_t * ui_labCancel;
lv_obj_t * ui_panelCheckUpdate;
lv_obj_t * ui_labUpdate1;
lv_obj_t * ui_spinUpdate;
lv_obj_t * ui_panelNoConnect;
lv_obj_t * ui_labUpdate6;


// SCREEN: ui_scrMusic
void ui_scrMusic_screen_init(void);
void ui_event_scrMusic(lv_event_t * e);
lv_obj_t * ui_scrMusic;
lv_obj_t * ui_imgLastMusic;
lv_obj_t * ui_imgNextMusic;
lv_obj_t * ui_imgStartMusic;
lv_obj_t * ui_imgEndMusic;
lv_obj_t * ui_labMusicHour;
lv_obj_t * ui_labMusicMin;
lv_obj_t * ui_labMusicDot;
lv_obj_t * ui_imgSound;
lv_obj_t * ui_imgMute;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_ai[1] = {&ui_img_ai07_png};
const lv_img_dsc_t * ui_imgset_background2_[1] = {&ui_img_background2_240_png};
const lv_img_dsc_t * ui_imgset_background3_[1] = {&ui_img_background3_240_png};
const lv_img_dsc_t * ui_imgset_background_[1] = {&ui_img_background_240_png};
const lv_img_dsc_t * ui_imgset_bg[3] = {&ui_img_bg1_png, &ui_img_bg2_png, &ui_img_bg3_png};
const lv_img_dsc_t * ui_imgset_btn_bg_[3] = {&ui_img_btn_bg_1_png, &ui_img_btn_bg_2_png, &ui_img_btn_bg_3_png};
const lv_img_dsc_t * ui_imgset_call[2] = {&ui_img_call1_png, &ui_img_call2_png};
const lv_img_dsc_t * ui_imgset_fanqie_[1] = {&ui_img_fanqie_1_png};
const lv_img_dsc_t * ui_imgset_heart[1] = {&ui_img_heart2_png};
const lv_img_dsc_t * ui_imgset_kaishi[1] = {&ui_img_kaishi1_png};
const lv_img_dsc_t * ui_imgset_kaishi_[1] = {&ui_img_kaishi_1_png};
const lv_img_dsc_t * ui_imgset_s[2] = {&ui_img_s1_png, &ui_img_s2_png};
const lv_img_dsc_t * ui_imgset_shezhi_[3] = {&ui_img_shezhi_1_png, &ui_img_shezhi_2_png, &ui_img_shezhi_3_png};
const lv_img_dsc_t * ui_imgset_752975614[1] = {&ui_img_2071213044};
const lv_img_dsc_t * ui_imgset_watch1_[1] = {&ui_img_watch1_170_png};
const lv_img_dsc_t * ui_imgset_watch2_[1] = {&ui_img_watch2_170_png};
const lv_img_dsc_t * ui_imgset_wave[2] = {&ui_img_wave1_png, &ui_img_wave2_png};
const lv_img_dsc_t * ui_imgset_1715410101[1] = {&ui_img_981806855};
const lv_img_dsc_t * ui_imgset_yonghu_[1] = {&ui_img_yonghu_1_png};
const lv_img_dsc_t * ui_imgset_1397978501[1] = {&ui_img_1718244669};

static void start_logo_animation(lv_timer_t * timer);
static void show_label_cb(lv_anim_t * a);

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

static void show_label_cb(lv_anim_t * a) {
    // 动画完成后的回调，显示label
    lv_obj_clear_flag(ui_labOpen, LV_OBJ_FLAG_HIDDEN);
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_scrOpen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        if(globalData.flag_config == 1){
            _ui_screen_change(&ui_scrWatch1, LV_SCR_LOAD_ANIM_FADE_ON, 50, 3000, &ui_scrWatch1_screen_init);
        }
        else{
            // 1. 先显示logo 2秒
            lv_timer_t * timer = lv_timer_create(
                (lv_timer_cb_t)start_logo_animation,  // 创建新的回调函数
                2000,  // 2秒后开始动画
                NULL
            );
            if(globalData.flag_first_connect == 1){
                lv_obj_add_flag(ui_labOpen, LV_OBJ_FLAG_HIDDEN);
                lv_obj_clear_flag(ui_pannelOpen, LV_OBJ_FLAG_HIDDEN);
            }else{
                lv_obj_clear_flag(ui_scrOpen, LV_OBJ_FLAG_HIDDEN);
                lv_obj_add_flag(ui_pannelOpen, LV_OBJ_FLAG_HIDDEN); 
            }
            
        }
    }
}

static void start_logo_animation(lv_timer_t * timer) {
    // 2. 开始logo动画
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_logo);
    lv_anim_set_values(&a, 0, -20);
    lv_anim_set_time(&a, 1000);
    lv_anim_set_path_cb(&a, lv_anim_path_linear);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    
    // 3. 设置动画结束回调，显示label
    lv_anim_set_ready_cb(&a, show_label_cb);
    
    lv_anim_start(&a);
    
    // 删除定时器
    lv_timer_del(timer);
}

void ui_event_scrWatch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_scrMenu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrWatch2, LV_SCR_LOAD_ANIM_MOVE_TOP, 50, 0, &ui_scrWatch2_screen_init);
    }
}
void ui_event_scrWatch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_scrMenu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrWatch1, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 50, 0, &ui_scrWatch1_screen_init);
    }
}
void ui_event_scrWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrMenu_screen_init);
    }
}
void ui_event_scrTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrMenu_screen_init);
    }
}
void ui_event_scrTomato(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrMenu_screen_init);
    }
}
void ui_event_scrMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrWatch1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrWatch1_screen_init);
    }
}
void ui_event_PalWatch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrWatch1, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrWatch1_screen_init);
    }
}
void ui_event_PalMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMusic, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrMusic_screen_init);
    }
}
void ui_event_PalWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrWeather, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrWeather_screen_init);
    }
}
void ui_event_PalTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTimer, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrTimer_screen_init);
    }
}
void ui_event_PalTomato(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTomato, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrTomato_screen_init);
    }
}
void ui_event_PalLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrLight, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrLight_screen_init);
    }
}
void ui_event_PalUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrUpdate, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_scrUpdate_screen_init);
    }
}
void ui_event_scrLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrMenu_screen_init);
    }
}

void ui_event_scrUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrMenu_screen_init);
    }
}
void ui_event_scrMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_scrMenu_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrOpen_screen_init();
    ui_scrWatch1_screen_init();
    ui_scrWatch2_screen_init();
    ui_scrWeather_screen_init();
    ui_scrTimer_screen_init();
    ui_scrTomato_screen_init();
    ui_scrMenu_screen_init();
    ui_scrLight_screen_init();
    ui_scrUpdate_screen_init();
    ui_scrMusic_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrOpen);
}
