// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "common/common.h"


// SCREEN: ui_scrOpen
void ui_scrOpen_screen_init(void);
void ui_event_scrOpen(lv_event_t * e);
extern lv_obj_t * ui_scrOpen;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_labOpen;
extern lv_obj_t * ui_pannelOpen;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_spinOpen;
// SCREEN: ui_scrWatch1
void ui_scrWatch1_screen_init(void);
void ui_event_scrWatch1(lv_event_t * e);
extern lv_obj_t * ui_scrWatch1;
extern lv_obj_t * ui_imgCharge;
extern lv_obj_t * ui_labPower;
extern lv_obj_t * ui_red_bar1;
extern lv_obj_t * ui_red_bar2;
extern lv_obj_t * ui_imgWatch1Cloudy;
extern lv_obj_t * ui_labTemp;
extern lv_obj_t * ui_labWeek;
extern lv_obj_t * ui_labDate;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_imgWatch1Rainy;
extern lv_obj_t * ui_imgWatch1Sunny;
extern lv_obj_t * ui_imgWatch1Snow;
extern lv_obj_t * ui_ArcPower1;
extern lv_obj_t * ui_dotWatch11;
extern lv_obj_t * ui_dotWatch12;
// SCREEN: ui_scrWatch2
void ui_scrWatch2_screen_init(void);
void ui_event_scrWatch2(lv_event_t * e);
extern lv_obj_t * ui_scrWatch2;
extern lv_obj_t * ui_imgCharge2;
extern lv_obj_t * ui_labPower2;
extern lv_obj_t * ui_red_bar3;
extern lv_obj_t * ui_red_bar4;
extern lv_obj_t * ui_imgWatch2Cloudy;
extern lv_obj_t * ui_labTemp2;
extern lv_obj_t * ui_labWeek2;
extern lv_obj_t * ui_labDate2;
extern lv_obj_t * ui_labTimeHour2;
extern lv_obj_t * ui_labTimeHour1;
extern lv_obj_t * ui_labTimeMin;
extern lv_obj_t * ui_sec_dot;
extern lv_obj_t * ui_imgWatch2Sunny;
extern lv_obj_t * ui_imgWatch2Rainy;
extern lv_obj_t * ui_imgWatch2Snow;
extern lv_obj_t * ui_ArcPower2;
extern lv_obj_t * ui_dotWatch21;
extern lv_obj_t * ui_dotWatch22;
// SCREEN: ui_scrWeather
void ui_scrWeather_screen_init(void);
void ui_event_scrWeather(lv_event_t * e);
extern lv_obj_t * ui_scrWeather;
extern lv_obj_t * ui_imgWeatherHum;
extern lv_obj_t * ui_labWeatherTemp;
extern lv_obj_t * ui_labWeatherHum;
extern lv_obj_t * ui_labWeatherArea;
extern lv_obj_t * ui_labWeatherTianqi;
extern lv_obj_t * ui_labWeatherMaxmin;
extern lv_obj_t * ui_labWeatherDate;
extern lv_obj_t * ui_imgWeatherRainy;
extern lv_obj_t * ui_imgWeatherSnow;
extern lv_obj_t * ui_imgWeatherCloudy;
extern lv_obj_t * ui_imgWeatherSunny;
// SCREEN: ui_scrTimer
void ui_scrTimer_screen_init(void);
void ui_event_scrTimer(lv_event_t * e);
extern lv_obj_t * ui_scrTimer;
extern lv_obj_t * ui_labelTimerSecond1;
extern lv_obj_t * ui_labelTimerMin1;
extern lv_obj_t * ui_labelTimerHour1;
extern lv_obj_t * ui_labelTimerDot1;
extern lv_obj_t * ui_labelTimerDot2;
extern lv_obj_t * ui_imgTimerStart;
extern lv_obj_t * ui_imgTimerPause;
extern lv_obj_t * ui_imgTimerRst;
// SCREEN: ui_scrTomato
void ui_scrTomato_screen_init(void);
void ui_event_scrTomato(lv_event_t * e);
extern lv_obj_t * ui_scrTomato;
extern lv_obj_t * ui_arcTomato;
extern lv_obj_t * ui_labelTomatoecond;
extern lv_obj_t * ui_labelTomatoMin;
extern lv_obj_t * ui_labelTomatoDot;
extern lv_obj_t * ui_imgTomatoStart;
extern lv_obj_t * ui_imgTomatoPause;
extern lv_obj_t * ui_imgTomatoCount;
extern lv_obj_t * ui_labelTomatoCount;
extern lv_obj_t * ui_labelTomatoX;
// SCREEN: ui_scrMenu
void ui_scrMenu_screen_init(void);
void ui_event_scrMenu(lv_event_t * e);
extern lv_obj_t * ui_scrMenu;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
void ui_event_PalWatch2(lv_event_t * e);
extern lv_obj_t * ui_PalWatch2;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label15;
void ui_event_PalMusic(lv_event_t * e);
extern lv_obj_t * ui_PalMusic;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label2;
void ui_event_PalWeather(lv_event_t * e);
extern lv_obj_t * ui_PalWeather;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label9;
void ui_event_PalTimer(lv_event_t * e);
extern lv_obj_t * ui_PalTimer;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label10;
void ui_event_PalTomato(lv_event_t * e);
extern lv_obj_t * ui_PalTomato;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label11;
void ui_event_PalLight(lv_event_t * e);
extern lv_obj_t * ui_PalLight;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label12;
void ui_event_PalUpdate(lv_event_t * e);
extern lv_obj_t * ui_PalUpdate;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel3;
// SCREEN: ui_scrLight
void ui_scrLight_screen_init(void);
void ui_event_scrLight(lv_event_t * e);
extern lv_obj_t * ui_scrLight;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_PalLightSetting;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_PalLightBreath;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_PalLightStay;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_PalLightRainbow;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_PalLightSky;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_PalLightWave;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel6;
// SCREEN: ui_scrUpdate
void ui_scrUpdate_screen_init(void);
void ui_event_scrUpdate(lv_event_t * e);
extern lv_obj_t * ui_scrUpdate;
extern lv_obj_t * ui_panelAlready;
extern lv_obj_t * ui_labUpdate2;
extern lv_obj_t * ui_labUpdate3;
extern lv_obj_t * ui_panelNewVersion;
extern lv_obj_t * ui_panelAlready1;
extern lv_obj_t * ui_labUpdate4;
extern lv_obj_t * ui_labUpdate5;
extern lv_obj_t * ui_buttonUpdate;
extern lv_obj_t * ui_labUpdate;
extern lv_obj_t * ui_buttonCancel;
extern lv_obj_t * ui_labCancel;
extern lv_obj_t * ui_panelCheckUpdate;
extern lv_obj_t * ui_labUpdate1;
extern lv_obj_t * ui_spinUpdate;
extern lv_obj_t * ui_panelNoConnect;
extern lv_obj_t * ui_labUpdate6;
// SCREEN: ui_scrMusic
void ui_scrMusic_screen_init(void);
void ui_event_scrMusic(lv_event_t * e);
extern lv_obj_t * ui_scrMusic;
extern lv_obj_t * ui_imgLastMusic;
extern lv_obj_t * ui_imgNextMusic;
extern lv_obj_t * ui_imgStartMusic;
extern lv_obj_t * ui_imgEndMusic;
extern lv_obj_t * ui_labMusicHour;
extern lv_obj_t * ui_labMusicMin;
extern lv_obj_t * ui_labMusicDot;
extern lv_obj_t * ui_imgSound;
extern lv_obj_t * ui_imgMute;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1718244669);    // assets/图片1.png
LV_IMG_DECLARE(ui_img_background2_240_png);    // assets/background2_240.png
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_btn_bg_1_png);    // assets/btn_bg_1.png
LV_IMG_DECLARE(ui_img_btn_bg_3_png);    // assets/btn_bg_3.png
LV_IMG_DECLARE(ui_img_weather_cloud_png);    // assets/weather_cloud.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_dayu_png);    // assets/dayu.png
LV_IMG_DECLARE(ui_img_981806855);    // assets/weather-1.png
LV_IMG_DECLARE(ui_img_daxue_png);    // assets/daxue.png
LV_IMG_DECLARE(ui_img_sec_dot_png);    // assets/sec_dot.png
LV_IMG_DECLARE(ui_img_background_240_png);    // assets/background_240.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/rain.png
LV_IMG_DECLARE(ui_img_dayu_grey_png);    // assets/dayu_grey.png
LV_IMG_DECLARE(ui_img_daxue_grey_png);    // assets/daxue_grey.png
LV_IMG_DECLARE(ui_img_1574789482);    // assets/w-1_grey.png
LV_IMG_DECLARE(ui_img_1502817839);    // assets/weather-1_grey.png
LV_IMG_DECLARE(ui_img_kaishi_png);    // assets/kaishi.png
LV_IMG_DECLARE(ui_img_ai07_png);    // assets/ai07.png
LV_IMG_DECLARE(ui_img_238951591);    // assets/zhongzhi-.png
LV_IMG_DECLARE(ui_img_1249513910);    // assets/番茄 (2).png
LV_IMG_DECLARE(ui_img_kaishi1_png);    // assets/kaishi1.png
LV_IMG_DECLARE(ui_img_fanqie_new_png);    // assets/fanqie_new.png
LV_IMG_DECLARE(ui_img_yonghu_png);    // assets/yonghu.png
LV_IMG_DECLARE(ui_img_yinyue_png);    // assets/yinyue.png
LV_IMG_DECLARE(ui_img_tianqi_new_png);    // assets/tianqi_new.png
LV_IMG_DECLARE(ui_img_jishiqi_png);    // assets/jishiqi.png
LV_IMG_DECLARE(ui_img_caihong_png);    // assets/caihong.png
LV_IMG_DECLARE(ui_img_1051555317);    // assets/a-shuaxingengxin.png
LV_IMG_DECLARE(ui_img_shezhi_png);    // assets/shezhi.png
LV_IMG_DECLARE(ui_img_1_round_solid_png);    // assets/1_round_solid.png
LV_IMG_DECLARE(ui_img_2_round_solid_png);    // assets/2_round_solid.png
LV_IMG_DECLARE(ui_img_3_round_solid_png);    // assets/3_round_solid.png
LV_IMG_DECLARE(ui_img_4_round_solid_png);    // assets/4_round_solid.png
LV_IMG_DECLARE(ui_img_5_round_solid_png);    // assets/5_round_solid.png
LV_IMG_DECLARE(ui_img_lastmusic_png);    // assets/lastmusic.png
LV_IMG_DECLARE(ui_img_nextmusic_png);    // assets/nextMusic.png
LV_IMG_DECLARE(ui_img_bofangmusic_png);    // assets/bofangMusic.png
LV_IMG_DECLARE(ui_img_zantingmusic_png);    // assets/zantingMusic.png
LV_IMG_DECLARE(ui_img_yinliang_png);    // assets/yinliang.png
LV_IMG_DECLARE(ui_img_jingyin_png);    // assets/jingyin.png
LV_IMG_DECLARE(ui_img_background3_240_png);    // assets/background3_240.png
LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_btn_bg_2_png);    // assets/btn_bg_2.png
LV_IMG_DECLARE(ui_img_call1_png);    // assets/call1.png
LV_IMG_DECLARE(ui_img_call2_png);    // assets/call2.png
LV_IMG_DECLARE(ui_img_fanqie_1_png);    // assets/fanqie_1.png
LV_IMG_DECLARE(ui_img_heart2_png);    // assets/heart2.png
LV_IMG_DECLARE(ui_img_kaishi_1_png);    // assets/kaishi_1.png
LV_IMG_DECLARE(ui_img_s1_png);    // assets/s1.png
LV_IMG_DECLARE(ui_img_s2_png);    // assets/s2.png
LV_IMG_DECLARE(ui_img_shezhi_1_png);    // assets/shezhi_1.png
LV_IMG_DECLARE(ui_img_shezhi_2_png);    // assets/shezhi_2.png
LV_IMG_DECLARE(ui_img_shezhi_3_png);    // assets/shezhi_3.png
LV_IMG_DECLARE(ui_img_2071213044);    // assets/Snipaste_2023-07-02_21-08-10.png
LV_IMG_DECLARE(ui_img_watch1_170_png);    // assets/watch1_170.png
LV_IMG_DECLARE(ui_img_watch2_170_png);    // assets/watch2_170.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/wave1.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets/wave2.png
LV_IMG_DECLARE(ui_img_yonghu_1_png);    // assets/yonghu_1.png



LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_chinesebig);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_Large);
LV_FONT_DECLARE(ui_font_chinesSmall);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif  // _SQUARELINE_PROJECT_UI_H
