// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "ui.h"
#include "common/common.h"


extern void ui_event_init(void);
extern lv_obj_t *black_screen;

extern void switch_to_black_screen(void);

#endif
